#filename kivytest.kv

<TheGrid>:
	encode: encode
	decode: decode
	result: result

	GridLayout:
		cols:1
		size:root.width, root.height

		Label:
			text: "What would you like to Encrypt?"
		TextInput:
			focus: True
			id: encode
		Button:
			on_press: root.encbtn()
			text: "^ENCRYPT^"

		TextInput:
			id: result

		Label:
			text: "What would you like to Decrypt?"
		TextInput:
			id: decode
		Button:
			on_press: root.decbtn()
			text: "^DECRYPT^"
